[tool.poetry]
name = "my-fastapi-app"
version = "0.1.0"
description = "FastAPI on Vercel"
authors = ["Hung <vuquochung2204@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
fastapi = "^0.78.0"
uvicorn = "^0.17.6"
